name:                miniGame
version:             0.1.0.0
github:              "githubuser/miniGame"
license:             BSD-3-Clause
author:              "Benoit Fraikin"
maintainer:          "benoit.fraikin@usherbrooke.ca"
copyright:           "GRIIS Université de Sherbrooke"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/miniGame#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal-game >= 1.9 && < 2
- text >= 2 && < 3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  miniGame-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - miniGame

tests:
  miniGame-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - miniGame
